import Image from "next/image";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { FaWhatsappSquare } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--montserrat",
  weight: "400",
});

export const metadata = {
  title: "Assuch Global",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={(inter.className, montserrat.variable)}>
        {children}
        <div
          style={{
            position: "fixed",
            bottom: "20px",
            right: "20px",
            zIndex: "99999",
          }}
        >
          <a href="https://wa.me/+2348035491849">
            <FaWhatsappSquare color="#00ADEF" size={30} />
          </a>
        </div>
      </body>
    </html>
  );
}
